package com.evaradrip.commerce.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProductPromotionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductPromotionAllPropertiesEquals(ProductPromotion expected, ProductPromotion actual) {
        assertProductPromotionAutoGeneratedPropertiesEquals(expected, actual);
        assertProductPromotionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductPromotionAllUpdatablePropertiesEquals(ProductPromotion expected, ProductPromotion actual) {
        assertProductPromotionUpdatableFieldsEquals(expected, actual);
        assertProductPromotionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductPromotionAutoGeneratedPropertiesEquals(ProductPromotion expected, ProductPromotion actual) {
        assertThat(actual)
            .as("Verify ProductPromotion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductPromotionUpdatableFieldsEquals(ProductPromotion expected, ProductPromotion actual) {
        assertThat(actual)
            .as("Verify ProductPromotion relevant properties")
            .satisfies(a -> assertThat(a.getPriority()).as("check priority").isEqualTo(expected.getPriority()))
            .satisfies(a -> assertThat(a.getIsExclusive()).as("check isExclusive").isEqualTo(expected.getIsExclusive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductPromotionUpdatableRelationshipsEquals(ProductPromotion expected, ProductPromotion actual) {
        // empty method
    }
}
