export enum NotificationType {
  ORDER_PLACED = 'ORDER_PLACED',

  ORDER_SHIPPED = 'ORDER_SHIPPED',

  ORDER_DELIVERED = 'ORDER_DELIVERED',

  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',

  PAYMENT_FAILED = 'PAYMENT_FAILED',

  PROMOTION = 'PROMOTION',

  WISHLIST = 'WISHLIST',

  REVIEW_RESPONSE = 'REVIEW_RESPONSE',

  GENERAL = 'GENERAL',
}
